# Generated by Django 5.0 on 2024-10-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['name'], 'verbose_name': 'Segmento'},
        ),
    ]
