# Generated by Django 5.0 on 2024-10-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_outflow_delete_inflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saída'},
        ),
    ]
