# Generated by Django 5.0 on 2024-10-30 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('outflows', '0003_alter_outflow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflow_positions', to='offices.office', verbose_name='Cargo'),
        ),
    ]
