# Generated by Django 5.0 on 2024-12-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0005_remove_outflow_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='sector',
            field=models.CharField(max_length=100, null=True, verbose_name='Setor'),
        ),
    ]
