# Generated by Django 5.0 on 2024-12-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0006_alter_outflow_sector'),
        ('segments', '0002_alter_segment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='segments.segment', verbose_name='Setor'),
        ),
    ]
