# Generated by Django 5.0 on 2024-12-05 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_segment'),
        ('outflows', '0020_alter_outflow_employee'),
        ('segments', '0002_alter_segment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='employees.employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='segments.segment', verbose_name='Setor'),
        ),
    ]
