# Generated by Django 5.0 on 2024-12-05 22:47

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0022_alter_outflow_sector'),
        ('segments', '0002_alter_segment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='sector',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='employee', chained_model_field='segment_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='segments.segment', verbose_name='Setor'),
        ),
    ]
